# Site settings
title: Your awesome title
email: joiey.seeley+pages@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging about software, family, and health & fitness
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bigtunacan.github.io" # the base hostname & protocol for your site
twitter_username: jseeley
github_username: bigtunacan

# Build settings
markdown: kramdown
